AMB-1276 add auth code flow
NHSDigital/hello-world-auth-examples pull request #27
Opened 2022-09-15 13:46 UTC by artronics

2022-09-23 13:18 UTC, ChewieCB requested changes

2022-09-23 13:18 UTC, ChewieCB commented on user-restricted-separate-auth-tutorials/nhs-login/java/README.md
> +NHS login is used to authenticate when the end user is a healthcare worker. With the separate authentication and authorisation pattern, authentication is done by NHS login. In exchange, you receive a
Pretty sure NHS Login is for patient end users and CIS2 is for healthcare workers, so this should read:
> when the end user is a patient

2022-09-23 13:18 UTC, ChewieCB commented on user-restricted-separate-auth-tutorials/nhs-login/java/pom.xml
> +	<artifactId>user-restricted-combined-auth-cis2</artifactId>
Artifact ID needs updating to `user-restricted-separate-auth-nhs-login` here

2022-09-25 18:19 UTC, artronics commented
@ChewieCB Thanks Jack. I addressed all your comments. I forgot to add the Dockerfile so this commit also contains Dockerfile.

2022-09-26 11:26 UTC, ChewieCB approved these changes

2022-09-26 11:27 UTC, merged